### ISSUE TITLE
Sort Tabnine results by Probability?

### ISSUE THREAD

**Issue by MatthewZMD** [TommyX12/company-tabnine#25]
Is it possible to sort the tabnine results by probability?

My [config](https://github.com/MatthewZMD/.emacs.d#company-tabnine)

The issue can also be seen [here](https://github.com/TommyX12/company-tabnine/blob/master/screenshot-deep-1.png)

**Comment by TommyX12** [comment]
TabNine's sorting strategy is not strictly by the probability number you mentioned (which is reported by the deep learning model). If you see the official blog at https://tabnine.com/blog/deep/ you will notice the same thing. TabNine uses a complex strategy to determine what is a better candidate, and the probability number is not the determining factor; it also take into account the length of the candidate etc.

The probability computed by language model (e.g. deep tabnine) is the probability that the completed text will **contain** this string; which means that a substring of a candidate will **always** have a higher probability. For example, if the probability of "hello world" appearing is 50%, then the probability of "hello" appearing is **at least** 50%. This is *not* the probability we want, since we would also like to rank certain long candidates higher. In other words, we are interested in the probability of **selecting** a candidate, and that's not necessarily the same as the probability of the candidate **appearing**.

**Comment by MatthewZMD** [comment]
Makes sense, thank you for this thorough answer
