### ISSUE TITLE
Windows Emacs: 'unzip' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by sumofat** [TommyX12/company-tabnine#46]
Can not install the binary due to this error being shown to me on windows.

**Comment by TommyX12** [comment]
This issue is caused by windows not having a trivial way of automatically unzipping the zip files, which is TabNine's new way of obtaining binaries.

Can you try going to `~/.TabNine/<version>/` and manually unzip the file? Make sure to unzip the content of the zip file into a folder in the same directory, with the folder name being the same as the zip file.

If this method works, I think the best solution, for now, is to add a special message for windows users to perform this unzipping manually.

**Comment by TommyX12** [comment]
The latest version should give Windows users (who don't have `unzip`) a message for how to unzip manually. Try updating to the latest version (once MELPA builds) and run the install binary command again.

**Comment by sumofat** [comment]
Yeah I did eventually figure out that was the case and did that worked ok.
Yes there definitely needs to be some documentation or warning to do that manually.

**Comment by licht1stein** [comment]
> This issue is caused by windows not having a trivial way of automatically unzipping the zip files, which is TabNine's new way of obtaining binaries.

Is `tar -xf archive.zip` trivial enough?

**Comment by licht1stein** [comment]
Anyway, here's an extremely simple workaround to get unzip in Windows.

Create an `unzip.bat` file and place it anywhere on your path:

```
@echo off
tar -xf %1
```

**Comment by TommyX12** [comment]
> > This issue is caused by windows not having a trivial way of automatically unzipping the zip files, which is TabNine's new way of obtaining binaries.
> 
> Is `tar -xf archive.zip` trivial enough?

Interesting, I wasn't familiar with Windows enough to know that `tar` is now built in. I learn something new everyday :)

Fixed in #48; feel free to take a look.

**Comment by licht1stein** [comment]
Cool, thanks!
